# Generated by Django 4.2.2 on 2023-08-06 21:16

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Receitas',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100, verbose_name='Nome')),
                ('receita', models.TextField(verbose_name='Receita')),
                ('tempo_preparo', models.CharField(max_length=100, verbose_name='Tempo de Preparo')),
                ('calorias', models.PositiveIntegerField(verbose_name='Calorias')),
                ('img', models.ImageField(blank=True, null=True, upload_to='exercicios/imagens', verbose_name='imagem descritiva')),
                ('video', models.CharField(blank=True, max_length=100, verbose_name='link do Video descritivo')),
                ('categoria', models.CharField(max_length=100, verbose_name='Categoria')),
                ('criado_em', models.DateTimeField(auto_now_add=True, verbose_name='criado em: ')),
                ('atualizado_em', models.DateTimeField(auto_now=True, verbose_name='atualizado em: ')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='receitas', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
