# Generated by Django 4.2.2 on 2023-08-06 21:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dietas', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='receitas',
            name='receita',
        ),
        migrations.AddField(
            model_name='receitas',
            name='ingredientes',
            field=models.TextField(default=1, verbose_name='Ingredientes'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='receitas',
            name='preparo',
            field=models.TextField(default=1, verbose_name='Preparo'),
            preserve_default=False,
        ),
    ]
