# Generated by Django 4.2.2 on 2023-08-09 19:36

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('dietas', '0002_remove_receitas_receita_receitas_ingredientes_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Plano_dieta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100, verbose_name='nome')),
                ('criado_em', models.DateTimeField(auto_now_add=True, verbose_name='criado em: ')),
                ('atualizado_em', models.DateTimeField(auto_now=True, verbose_name='atualizado em: ')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='dieta', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Refeicoes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100, verbose_name='nome')),
                ('descricao', models.TextField(blank=True, verbose_name='Recomendações:')),
                ('total_calorias', models.IntegerField(blank=True, verbose_name='Total de calorias')),
                ('dieta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='refeicoes', to='dietas.plano_dieta')),
            ],
        ),
        migrations.CreateModel(
            name='Alimentos_da_Refeicao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantidade', models.PositiveIntegerField(default=1, verbose_name='Quantidade')),
                ('receita', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dietas.receitas')),
                ('refeicao', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='alimentos', to='dietas.plano_dieta')),
            ],
        ),
    ]
