# Generated by Django 4.2.2 on 2023-08-09 20:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dietas', '0003_plano_dieta_refeicoes_alimentos_da_refeicao'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='refeicoes',
            name='descricao',
        ),
        migrations.AddField(
            model_name='refeicoes',
            name='tipo_refeicao',
            field=models.CharField(blank=True, max_length=100, verbose_name='Tipo de Refeição'),
        ),
    ]
