# Generated by Django 4.2.2 on 2023-08-09 20:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dietas', '0004_remove_refeicoes_descricao_refeicoes_tipo_refeicao'),
    ]

    operations = [
        migrations.AlterField(
            model_name='refeicoes',
            name='total_calorias',
            field=models.IntegerField(blank=True, null=True, verbose_name='Total de calorias'),
        ),
    ]
