# Generated by Django 4.2.2 on 2023-08-09 21:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dietas', '0005_alter_refeicoes_total_calorias'),
    ]

    operations = [
        migrations.AlterField(
            model_name='alimentos_da_refeicao',
            name='refeicao',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='alimentos', to='dietas.refeicoes'),
        ),
    ]
