# Generated by Django 4.2.2 on 2023-08-10 12:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dietas', '0006_alter_alimentos_da_refeicao_refeicao'),
    ]

    operations = [
        migrations.AlterField(
            model_name='alimentos_da_refeicao',
            name='quantidade',
            field=models.CharField(max_length=200, verbose_name='Quantidade'),
        ),
    ]
