# Generated by Django 4.2.2 on 2023-06-13 15:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('treinos', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='exercicios',
            name='descricao',
            field=models.TextField(blank=True, default=1, verbose_name='Descricao'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='exercicios',
            name='video',
            field=models.CharField(blank=True, max_length=100, verbose_name='link do Video descritivo'),
        ),
        migrations.AlterField(
            model_name='exercicios_do_treino',
            name='exercicio',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='exercicios_do_treino', to='treinos.exercicios', unique=True),
        ),
        migrations.AlterField(
            model_name='treinos',
            name='descricao',
            field=models.TextField(blank=True, verbose_name='Descricao'),
        ),
    ]
