# Generated by Django 4.2.2 on 2023-07-24 20:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('treinos', '0002_exercicios_categoria'),
    ]

    operations = [
        migrations.AddField(
            model_name='treinos',
            name='img',
            field=models.ImageField(blank=True, null=True, upload_to='treinos/imagens', verbose_name='imagem descritiva'),
        ),
    ]
