# Generated by Django 4.0.4 on 2023-06-13 16:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('treinos', '0002_alter_exercicios_descricao_alter_exercicios_video_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='exercicios_do_treino',
            name='exercicio',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='exercicios_do_treino', to='treinos.exercicios'),
        ),
    ]
