# Generated by Django 4.2.2 on 2023-07-24 21:11

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('treinos', '0004_treinos_categoria'),
    ]

    operations = [
        migrations.AddField(
            model_name='exercicios',
            name='atualizado_em',
            field=models.DateTimeField(auto_now=True, verbose_name='atualizado em: '),
        ),
        migrations.AddField(
            model_name='exercicios',
            name='criado_em',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now, verbose_name='criado em: '),
            preserve_default=False,
        ),
    ]
