# Generated by Django 4.2.2 on 2023-08-06 21:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('treinos', '0006_treinos_atualizado_em_treinos_criado_em'),
    ]

    operations = [
        migrations.AlterField(
            model_name='exercicios_do_treino',
            name='exercicio',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='exercicio_do_treino', to='treinos.exercicios'),
        ),
        migrations.AlterField(
            model_name='exercicios_do_treino',
            name='treino',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='exercicios_do_treino', to='treinos.treinos'),
        ),
    ]
